//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIProjectClient.FordonsPassageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FordonsPassageServiceReference.IFordonsPassageService")]
    public interface IFordonsPassageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFordonsPassageService/HämtaFordonsPassager", ReplyAction="http://tempuri.org/IFordonsPassageService/HämtaFordonsPassagerResponse")]
        System.Xml.Linq.XElement HämtaFordonsPassager(System.Xml.Linq.XElement förfrågan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFordonsPassageService/HämtaFordonsPassager", ReplyAction="http://tempuri.org/IFordonsPassageService/HämtaFordonsPassagerResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> HämtaFordonsPassagerAsync(System.Xml.Linq.XElement förfrågan);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFordonsPassageServiceChannel : IIProjectClient.FordonsPassageServiceReference.IFordonsPassageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FordonsPassageServiceClient : System.ServiceModel.ClientBase<IIProjectClient.FordonsPassageServiceReference.IFordonsPassageService>, IIProjectClient.FordonsPassageServiceReference.IFordonsPassageService {
        
        public FordonsPassageServiceClient() {
        }
        
        public FordonsPassageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FordonsPassageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FordonsPassageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FordonsPassageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement HämtaFordonsPassager(System.Xml.Linq.XElement förfrågan) {
            return base.Channel.HämtaFordonsPassager(förfrågan);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> HämtaFordonsPassagerAsync(System.Xml.Linq.XElement förfrågan) {
            return base.Channel.HämtaFordonsPassagerAsync(förfrågan);
        }
    }
}
